// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Mon Jul 05 13:32:38 2021

Project1 Project1_inst
(
	.op_a(op_a_sig) ,	// input [7:0] op_a_sig
	.op_b(op_b_sig) ,	// input [7:0] op_b_sig
	.op_code(op_code_sig) ,	// input [1:0] op_code_sig
	.out(out_sig) ,	// output [7:0] out_sig
	.carry_out(carry_out_sig) 	// output  carry_out_sig
);

defparam Project1_inst.ADD = 'b00;
defparam Project1_inst.SUB = 'b01;
defparam Project1_inst.TWO = 'b10;
defparam Project1_inst.XOR = 'b11;
